version: '3.7'
services:
  genenotebook:
    image: quay.io/abretaud/genenotebook:master
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    volumes:
      - ./data/refdata:/data/refdata
    environment:
      NODE_OPTIONS: "--max-old-space-size=8192"
      MONGO_URL: "mongodb://mongodb:27017/genenotebook"
      RUN_MODE: "prod"

  mongodb:
    image: mongo
    volumes:
      - ./data/db:/data/db
